// <auto-generated />
using System;
using DoctorTask.DataAcess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoctorTask.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoctorTask.Models.Appointement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("PatientEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Problem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("TimeSlot")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("Appointements");
                });

            modelBuilder.Entity("DoctorTask.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpecilizationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpecilizationId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ahmed@test.com",
                            ImageUrl = "team-1.jpg",
                            Name = "Dr. Ahmed",
                            Phone = "0100000001",
                            SpecilizationId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "sara@test.com",
                            ImageUrl = "team-2.jpg",
                            Name = "Dr. Sara",
                            Phone = "0100000002",
                            SpecilizationId = 2
                        },
                        new
                        {
                            Id = 3,
                            Email = "ali@test.com",
                            ImageUrl = "team-3.jpg",
                            Name = "Dr. Ali",
                            Phone = "0100000003",
                            SpecilizationId = 3
                        },
                        new
                        {
                            Id = 4,
                            Email = "omar@test.com",
                            ImageUrl = "team-4.jpg",
                            Name = "Dr. Omar",
                            Phone = "0100000004",
                            SpecilizationId = 4
                        },
                        new
                        {
                            Id = 5,
                            Email = "nada@test.com",
                            ImageUrl = "team5.jpg",
                            Name = "Dr. Nada",
                            Phone = "0100000005",
                            SpecilizationId = 5
                        },
                        new
                        {
                            Id = 6,
                            Email = "hassan@test.com",
                            ImageUrl = "team6.jpg",
                            Name = "Dr. Hassan",
                            Phone = "0100000006",
                            SpecilizationId = 6
                        },
                        new
                        {
                            Id = 7,
                            Email = "laila@test.com",
                            ImageUrl = "team7.jpg",
                            Name = "Dr. Laila",
                            Phone = "0100000007",
                            SpecilizationId = 7
                        },
                        new
                        {
                            Id = 8,
                            Email = "karim@test.com",
                            ImageUrl = "team8.jpg",
                            Name = "Dr. Karim",
                            Phone = "0100000008",
                            SpecilizationId = 8
                        });
                });

            modelBuilder.Entity("DoctorTask.Models.Specilization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("specilizations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Heart specialist",
                            Name = "Cardiology"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Skin specialist",
                            Name = "Dermatology"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Brain specialist",
                            Name = "Neurology"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Bone specialist",
                            Name = "Orthopedics"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Children specialist",
                            Name = "Pediatrics"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Eye specialist",
                            Name = "Ophthalmology"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Ear Nose Throat",
                            Name = "ENT"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Teeth specialist",
                            Name = "Dentistry"
                        });
                });

            modelBuilder.Entity("DoctorTask.Models.Appointement", b =>
                {
                    b.HasOne("DoctorTask.Models.Doctor", "Doctor")
                        .WithMany("Appointements")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("DoctorTask.Models.Doctor", b =>
                {
                    b.HasOne("DoctorTask.Models.Specilization", "Specilization")
                        .WithMany()
                        .HasForeignKey("SpecilizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specilization");
                });

            modelBuilder.Entity("DoctorTask.Models.Doctor", b =>
                {
                    b.Navigation("Appointements");
                });
#pragma warning restore 612, 618
        }
    }
}
